{% set name = "pycatflow" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pycatflow-{{ version }}.tar.gz
  sha256: 3ef8d3abbd7857fad298c22a2b9f11a2fa4ac7a9250f993eeab2da349cfb60e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - drawsvg
    - matplotlib-base
    - python >=3.6

test:
  imports:
    - pycatflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bumatic/PyCatFlow
  summary: A tool for visualizing categorical data over time.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
